print("Hello SoftUni")
print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
print(10)
name = input("Как се казваш?   ")
print("Здравей ", name)
a = int(input("Въведи страна на квадрат - "))
area = a * a
print("Площта му е ", area)